version: '3.9'

services:
  app:
    container_name: care_service_provider_app
    build:
      context: ./
      dockerfile: docker/development/app/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - type: bind
        source: ./www
        target: /var/www
    links:
      - database

  database:
    container_name: care_service_provider_db
    build:
      context: ./
      dockerfile: docker/development/database/Dockerfile
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    ports:
      - "54328:5432"
    environment:
      POSTGRES_DB: care_service
      POSTGRES_USER: care_service_user
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    command: -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"

  tbls:
    container_name: care_service_provider_dbdoc
    image: k1low/tbls:latest
    volumes:
      - ./:/work
    command: doc postgres://care_service_user:secret@care_service_provider_db:5432/care_service ./docs/schema --force
    profiles:
      - dbdoc

volumes:
  pgsql_data:
    driver: local