#!/bin/sh
set -e

RAILS_PORT=8080
if [ -n "$PORT" ]; then
  RAILS_PORT=$PORT
fi

# Remove a potentially pre-existing server.pid for Rails.
rm -f /var/www/tmp/pids/server.pid

# Run
rails s -p $RAILS_PORT -b 0.0.0.0